# Generated by Django 3.2.7 on 2022-04-16 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0016_alter_holdings_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total_quantity', models.IntegerField()),
                ('quantity_per_user', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo', to='simulator.league')),
            ],
            options={
                'verbose_name_plural': 'IPOs',
            },
        ),
        migrations.AddField(
            model_name='stocks',
            name='listed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ipo_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_application', to='simulator.ipo')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_application', to='simulator.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IPO Applications',
            },
        ),
        migrations.AddField(
            model_name='ipo',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo', to='simulator.stocks'),
        ),
    ]
