# Generated by Django 3.2.7 on 2022-04-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0017_auto_20220416_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='name',
        ),
    ]
