# Generated by Django 3.2.7 on 2022-04-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0018_remove_ipo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='description',
        ),
    ]
