# Generated by Django 3.2.7 on 2022-04-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0019_remove_ipo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo',
            name='price',
        ),
    ]
