# Generated by Django 3.2.7 on 2022-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0020_remove_ipo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipo_application',
            name='league',
        ),
        migrations.RemoveField(
            model_name='ipo_application',
            name='price',
        ),
        migrations.AddField(
            model_name='ipo_application',
            name='status',
            field=models.CharField(default='Not Applied', max_length=100),
            preserve_default=False,
        ),
    ]
