# Generated by Django 3.2.7 on 2022-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_ipo_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='status',
            field=models.CharField(default='Completed', max_length=100),
            preserve_default=False,
        ),
    ]
