# Generated by Django 3.2.7 on 2022-04-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0024_alter_transaction_ttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ttype',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('SHORT', 'SHORT'), ('SQUARE OFF', 'SQUARE OFF')], max_length=100),
        ),
    ]
