# Generated by Django 3.2.7 on 2022-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0025_alter_transaction_ttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='trading_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
