# Generated by Django 3.2.7 on 2022-04-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0027_auto_20220416_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=10385760),
        ),
    ]
